### ISSUE TITLE
URLs are not being validated on `Link` creation

### ISSUE THREAD

**Issue by Michael-Liendo** [whizzes/linx#2]
when posting to the `/new `route, the server should check if the body being passed to it is a url

**Comment by EstebanBorai** [comment]
> when posting to the `/new `route, the server should check if the body being passed to it is a url

Hi @Michael-Liendo,

When creating links we do `Uri` parsing from a `String` here:

https://github.com/whizzes/linx/blob/cfb8fc367732fe3f9c8dba3ae41a63ec0011a821/src/handlers/create_link.rs#L18

I'm curious about the input involved in your issue, can you share an example of a piece of text you used that wasn't validated properly?

I will be adding tests for these validations.

**Comment by Michael-Liendo** [comment]
> > when posting to the `/new `route, the server should check if the body being passed to it is a url
> 
> Hi @Michael-Liendo,
> 
> When creating links we do `Uri` parsing from a `String` here:
> 
> https://github.com/whizzes/linx/blob/cfb8fc367732fe3f9c8dba3ae41a63ec0011a821/src/handlers/create_link.rs#L18
> 
> I'm curious about the input involved in your issue, can you share an example of a piece of text you used that wasn't validated properly?
> 
> I will be adding tests for these validations.

Sure! here it is
![image](https://user-images.githubusercontent.com/70660410/190450898-1971f7ad-5775-41dc-80eb-17523fa5ffd7.png)

**Comment by Michael-Liendo** [comment]
This is very cool 🚀
